spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_db?useSSL=false&serverTimezone=UTC&&useLegacyDatetimeCode=false
    username: root
    password: root1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 4KB
      max-file-size: 500MB
      max-request-size: 515MB